services:
  postgres:
    image: 'postgres:17-alpine'
    platform: linux/amd64
    environment:
      - 'POSTGRES_DB=starbucks'
      - 'POSTGRES_PASSWORD=starbucks123'
      - 'POSTGRES_USER=starbucks'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      org.springframework.boot.service-connection: postgres

volumes:
  postgres_data:
